# Generated by Django 5.1.1 on 2024-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='desc', max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
